[package]
cairo-version = "=2.7.0-rc.3"
name = "starkludo"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate apply"
spawn = "./scripts/spawn.sh"
move = "./scripts/move.sh"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-alpha.4" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xprinceibs"

[tool.dojo.env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0xb3ff441a68610b30fd5e2abbf3a1548eb6ba6f3559f2862bf2dc757e5828ca"
private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"
# world_address = "0x3fc79ccfd72c1450d2ccb73c5c521a7ec68b6c6af0caf96a0f1c39ce58876c8"  # Uncomment and update this line with your world address.

[tool.dojo.world]
name = "StarkLudo"
description = "Ludo game on Starknet"
cover_uri = ""
icon_uri = ""
website = "https://github.com/sivicstudio/starkludo"
seed = "starkludo"

[tool.dojo.world.namespace]
default = "starkludo"

[tool.dojo.world.socials]
x = "https://x.com/ludoonstarknet"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"
