kind = "DojoContract"
class_hash = "0x1051562de62212122f575573026755bd6b6710a99808072c8d9a0c54248f75b"
original_class_hash = "0x1051562de62212122f575573026755bd6b6710a99808072c8d9a0c54248f75b"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/starkludo-actions-6e36eb0d.json"
reads = []
writes = []
init_calldata = []
tag = "starkludo-actions"
systems = [
    "spawn",
    "move",
]
manifest_name = "starkludo-actions-6e36eb0d"
