kind = "DojoContract"
class_hash = "0x4b3c29628dab01e08eba58707af15743108c4e7d2e169555375efc8f1ee6e2c"
original_class_hash = "0x4b3c29628dab01e08eba58707af15743108c4e7d2e169555375efc8f1ee6e2c"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/starkludo-PlayerActions-20dad3ac.json"
reads = []
writes = []
init_calldata = []
tag = "starkludo-PlayerActions"
systems = [
    "create",
    "update_username",
]
manifest_name = "starkludo-PlayerActions-20dad3ac"
