name: Test Dojo contracts
on: [push, pull_request]

jobs:
  sozo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl -L https://install.dojoengine.org | bash
      - run: /home/runner/.config/.dojo/bin/dojoup -v v1.0.0-alpha.13
      - run: |
          cd onchain
          /home/runner/.config/.dojo/bin/sozo build
          /home/runner/.config/.dojo/bin/sozo test
